### ISSUE TITLE
数据是否按照格式？

### ISSUE THREAD

**Issue by AnnKwok** [bigdata-labs/analysis-sogou-log#1]
我下载到的Sogou完整版的数据并没有按照 
访问时间\t用户ID\t[查询词]\t该URL在返回结果中的排名\t用户点击的顺序号\t用户点击的URL
这样的格式，
而是缺少了访问时间，请问你下载到的数据也是这样吗

**Comment by AnnKwok** [comment]
还有下载到的数据是2006年8月的，并不是2008年6月的

**Comment by zacker330** [comment]
年代久远，目前的数据格式是否还和我之前试验的相同，我也不知道。这个你自己做一下调整就好。
